export const types = {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",

    GET_DETAILS_USER: "GET_DETAILS_USER",
    GET_DETAILS_USER_SUCCESS: "GET_DETAILS_USER_SUCCESS",
    GET_DETAILS_USER_FAILURE: "GET_DETAILS_USER_FAILURE",
}